replicaCount: 1

image:
  repository: postgres
  tag: "13"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 1234
  POSTGRES_DB: db

persistence:
  enabled: true
  size: 8Gi
  storageClass: ""

resources: {}
