replicaCount: 1

image:
  repository: omalik26/silly-demo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  create: true
  name: ""

env:
  DB_ENDPOINT: postgresql
  DB_PORT: 5432
  DB_USER: postgres
  DB_PASS: 1234
  DB_NAME: db

resources: {}
