apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "silly-demo.fullname" . }}
  labels:
    {{- include "silly-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "silly-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "silly-demo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DB_ENDPOINT
              value: {{ .Values.env.DB_ENDPOINT }}
            - name: DB_PORT
              value: "{{ .Values.env.DB_PORT }}"
            - name: DB_USER
              value: {{ .Values.env.DB_USER }}
            - name: DB_PASS
              value: {{ .Values.env.DB_PASS }}
            - name: DB_NAME
              value: {{ .Values.env.DB_NAME }}
